/* ==========================================================
   Pediatric Camp Analytics — dashboard logic
   Consumes ../output/pediatric_camp_data.json and summary.json
   (generated by scripts/etl.py). No raw CSVs are ever touched
   by the browser.
   ========================================================== */

const DATA_URL = "../output/pediatric_camp_data.json";
const SUMMARY_URL = "../output/summary.json";
const IMAGE_CANDIDATES = ["camp-1.jpg", "camp-2.jpg", "camp-3.jpg", "camp-4.jpg", "camp-5.jpg"];

const CHART_COLORS = ["#1F6F6B", "#D9822B", "#BD4A3F", "#3F6E8C", "#2F8A5C", "#8B6BB0"];

let ALL_RECORDS = [];
let charts = {};

const els = {
  kpiGrid: document.getElementById("kpiGrid"),
  filterGender: document.getElementById("filterGender"),
  filterAgeGroup: document.getElementById("filterAgeGroup"),
  filterBmi: document.getElementById("filterBmi"),
  filterDate: document.getElementById("filterDate"),
  filterScreening: document.getElementById("filterScreening"),
  screeningFilterGroup: document.getElementById("screeningFilterGroup"),
  resetFilters: document.getElementById("resetFilters"),
  lastUpdated: document.getElementById("lastUpdated"),
  footerRecordCount: document.getElementById("footerRecordCount"),
};

init();

async function init() {
  setupCarousel();
  try {
    const [dataResp, summaryResp] = await Promise.all([fetch(DATA_URL), fetch(SUMMARY_URL)]);
    const data = await dataResp.json();
    const summary = await summaryResp.json();

    ALL_RECORDS = data.records || [];
    els.footerRecordCount.textContent = ALL_RECORDS.length.toLocaleString();

    const updatedAt = summary.generated_at ? new Date(summary.generated_at) : null;
    els.lastUpdated.textContent = "Last Updated: " + (updatedAt ? updatedAt.toLocaleString() : "—");

    buildFilterOptions(ALL_RECORDS);
    attachFilterListeners();
    render(ALL_RECORDS);
  } catch (err) {
    console.error("Failed to load dashboard data:", err);
    els.kpiGrid.innerHTML = `<div class="kpi-card"><div class="kpi-label">Could not load output/pediatric_camp_data.json — run the ETL pipeline first (python scripts/etl.py).</div></div>`;
  }
}

/* ---------------- Carousel ---------------- */

function setupCarousel() {
  const track = document.getElementById("carouselTrack");
  const dotsWrap = document.getElementById("carouselDots");
  const slides = [];

  IMAGE_CANDIDATES.forEach((name, i) => {
    const img = new Image();
    img.onload = () => addSlide(name, i);
    img.onerror = () => {}; // gracefully skip missing images
    img.src = "../images/" + name;
  });

  const addedIndices = new Set();
  function addSlide(name) {
    if (addedIndices.has(name)) return;
    addedIndices.add(name);
    const slide = document.createElement("div");
    slide.className = "carousel-slide";
    slide.innerHTML = `<img src="../images/${name}" alt="Pediatric camp photograph" loading="lazy">`;
    track.appendChild(slide);
    slides.push(slide);

    const dot = document.createElement("button");
    dot.setAttribute("aria-label", "Go to photo " + slides.length);
    dot.addEventListener("click", () => goTo(slides.length - 1));
    dotsWrap.appendChild(dot);

    refreshDots();
  }

  let current = 0;
  let timer = null;

  function refreshDots() {
    [...dotsWrap.children].forEach((d, i) => d.classList.toggle("active", i === current));
  }

  function goTo(index) {
    if (!slides.length) return;
    current = (index + slides.length) % slides.length;
    track.style.transform = `translateX(-${current * 100}%)`;
    refreshDots();
    restartAuto();
  }

  function restartAuto() {
    if (timer) clearInterval(timer);
    timer = setInterval(() => goTo(current + 1), 5000);
  }

  document.getElementById("prevBtn").addEventListener("click", () => goTo(current - 1));
  document.getElementById("nextBtn").addEventListener("click", () => goTo(current + 1));

  setTimeout(restartAuto, 1200);
}

/* ---------------- Filters ---------------- */

function uniqueSorted(values) {
  return [...new Set(values.filter((v) => v !== null && v !== undefined && v !== ""))].sort();
}

function ageGroup(age) {
  if (age === null || age === undefined) return null;
  if (age <= 5) return "0-5";
  if (age <= 10) return "6-10";
  if (age <= 15) return "11-15";
  if (age <= 18) return "16-18";
  return "19+";
}

function buildFilterOptions(records) {
  fillSelect(els.filterGender, uniqueSorted(records.map((r) => r.Gender)));

  const ageOrder = ["0-5", "6-10", "11-15", "16-18", "19+"];
  const ages = uniqueSorted(records.map((r) => ageGroup(r.Age_Years))).sort(
    (a, b) => ageOrder.indexOf(a) - ageOrder.indexOf(b)
  );
  fillSelect(els.filterAgeGroup, ages);

  fillSelect(els.filterBmi, uniqueSorted(records.map((r) => r.BMI_Status)));

  const dates = uniqueSorted(
    records.map((r) => (r.Created_DateTime ? r.Created_DateTime.split(",")[0].trim() : null))
  );
  fillSelect(els.filterDate, dates);

  if (records.some((r) => "Dental_Caries" in r) || records.some((r) => "Vision_Right_Eye" in r)) {
    els.screeningFilterGroup.hidden = false;
    fillSelect(els.filterScreening, ["Dental", "Vision", "Height/Weight"]);
  }
}

function fillSelect(select, values) {
  values.forEach((v) => {
    const opt = document.createElement("option");
    opt.value = v;
    opt.textContent = v;
    select.appendChild(opt);
  });
}

function attachFilterListeners() {
  [els.filterGender, els.filterAgeGroup, els.filterBmi, els.filterDate, els.filterScreening].forEach((sel) =>
    sel.addEventListener("change", applyFilters)
  );
  els.resetFilters.addEventListener("click", () => {
    [els.filterGender, els.filterAgeGroup, els.filterBmi, els.filterDate, els.filterScreening].forEach(
      (sel) => (sel.value = "")
    );
    applyFilters();
  });
}

function applyFilters() {
  let filtered = ALL_RECORDS;
  if (els.filterGender.value) filtered = filtered.filter((r) => r.Gender === els.filterGender.value);
  if (els.filterAgeGroup.value) filtered = filtered.filter((r) => ageGroup(r.Age_Years) === els.filterAgeGroup.value);
  if (els.filterBmi.value) filtered = filtered.filter((r) => r.BMI_Status === els.filterBmi.value);
  if (els.filterDate.value)
    filtered = filtered.filter(
      (r) => r.Created_DateTime && r.Created_DateTime.split(",")[0].trim() === els.filterDate.value
    );
  if (els.filterScreening.value) {
    const s = els.filterScreening.value;
    filtered = filtered.filter((r) => {
      if (s === "Dental") return !!(r.Dental_Caries || r.Dental_Remarks);
      if (s === "Vision") return !!(r.Vision_Right_Eye || r.Vision_Left_Eye);
      if (s === "Height/Weight") return r.Height_cm != null && r.Weight_kg != null;
      return true;
    });
  }
  render(filtered);
}

/* ---------------- KPIs ---------------- */

function computeKpis(records) {
  const n = records.length;
  const kpis = [{ label: "Total Pediatric Students", value: n, accent: "" }];

  const male = records.filter((r) => r.Gender === "Male").length;
  const female = records.filter((r) => r.Gender === "Female").length;
  if (male || female) {
    kpis.push({ label: "Male Students", value: male, accent: "slate" });
    kpis.push({ label: "Female Students", value: female, accent: "amber" });
    const other = n - male - female;
    if (other > 0) kpis.push({ label: "Other / Unknown Gender", value: other, accent: "" });
  }

  const ages = records.map((r) => r.Age_Years).filter((v) => v != null);
  if (ages.length) kpis.push({ label: "Average Age", value: avg(ages).toFixed(1), accent: "" });

  const bmis = records.map((r) => r.BMI).filter((v) => v != null);
  if (bmis.length) kpis.push({ label: "Average BMI", value: avg(bmis).toFixed(1), accent: "" });

  const bmiStatuses = records.map((r) => r.BMI_Status).filter(Boolean);
  if (bmiStatuses.length) {
    kpis.push({ label: "Normal BMI", value: count(bmiStatuses, "Normal"), accent: "sage" });
    kpis.push({ label: "Underweight", value: count(bmiStatuses, "Underweight"), accent: "brick" });
    kpis.push({ label: "Overweight", value: count(bmiStatuses, "Overweight"), accent: "amber" });
    const obese = count(bmiStatuses, "Obese");
    if (obese > 0) kpis.push({ label: "Obese", value: obese, accent: "brick" });
  }

  const dental = records.filter((r) => r.Dental_Caries != null || r.Dental_Remarks != null).length;
  if (dental) kpis.push({ label: "Dental Screening Count", value: dental, accent: "" });

  const vision = records.filter((r) => r.Vision_Right_Eye != null || r.Vision_Left_Eye != null).length;
  if (vision) kpis.push({ label: "Vision Screening Count", value: vision, accent: "" });

  return kpis;
}

function avg(arr) {
  return arr.reduce((a, b) => a + b, 0) / arr.length;
}
function count(arr, val) {
  return arr.filter((v) => v === val).length;
}

function renderKpis(records) {
  const kpis = computeKpis(records);
  els.kpiGrid.innerHTML = kpis
    .map(
      (k) => `
      <div class="kpi-card ${k.accent ? "accent-" + k.accent : ""}">
        <div class="kpi-value">${k.value}</div>
        <div class="kpi-label">${k.label}</div>
      </div>`
    )
    .join("");
}

/* ---------------- Charts ---------------- */

function tally(records, field, order) {
  const counts = {};
  records.forEach((r) => {
    const v = r[field];
    if (v === null || v === undefined || v === "") return;
    counts[v] = (counts[v] || 0) + 1;
  });
  let labels = Object.keys(counts);
  if (order) labels = order.filter((l) => labels.includes(l));
  return { labels, values: labels.map((l) => counts[l]) };
}

function renderChart(id, cardId, type, chartData, options = {}) {
  const card = document.getElementById(cardId);
  if (!chartData.labels.length) {
    card.classList.add("empty");
    return;
  }
  card.classList.remove("empty");
  const ctx = document.getElementById(id).getContext("2d");
  if (charts[id]) charts[id].destroy();
  charts[id] = new Chart(ctx, {
    type,
    data: {
      labels: chartData.labels,
      datasets: [
        {
          data: chartData.values,
          backgroundColor: chartData.labels.map((_, i) => CHART_COLORS[i % CHART_COLORS.length]),
          borderRadius: type === "bar" ? 4 : 0,
          borderWidth: type === "doughnut" ? 2 : 0,
          borderColor: "#ffffff",
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: { display: type === "doughnut", position: "bottom", labels: { boxWidth: 12, font: { family: "Public Sans" } } },
        tooltip: { titleFont: { family: "Public Sans" }, bodyFont: { family: "Public Sans" } },
      },
      scales:
        type === "bar"
          ? {
              y: { beginAtZero: true, ticks: { precision: 0 } },
              x: { grid: { display: false } },
            }
          : undefined,
      ...options,
    },
  });
}

function renderCharts(records) {
  renderChart("chartGender", "card-gender", "doughnut", tally(records, "Gender"));
  renderChart(
    "chartAge",
    "card-age",
    "bar",
    (() => {
      const groups = records.map((r) => ageGroup(r.Age_Years));
      const counts = {};
      groups.forEach((g) => {
        if (g) counts[g] = (counts[g] || 0) + 1;
      });
      const order = ["0-5", "6-10", "11-15", "16-18", "19+"];
      const labels = order.filter((o) => counts[o]);
      return { labels, values: labels.map((l) => counts[l]) };
    })()
  );
  renderChart("chartBmi", "card-bmi", "bar", tally(records, "BMI_Status", ["Underweight", "Normal", "Overweight", "Obese", "Needs Review"]));

  const screeningLabels = [];
  const screeningValues = [];
  const dental = records.filter((r) => r.Dental_Caries != null || r.Dental_Remarks != null).length;
  const vision = records.filter((r) => r.Vision_Right_Eye != null || r.Vision_Left_Eye != null).length;
  const hw = records.filter((r) => r.Height_cm != null && r.Weight_kg != null).length;
  if (dental) { screeningLabels.push("Dental"); screeningValues.push(dental); }
  if (vision) { screeningLabels.push("Vision"); screeningValues.push(vision); }
  if (hw) { screeningLabels.push("Height/Weight"); screeningValues.push(hw); }
  renderChart("chartScreening", "card-screening", "bar", { labels: screeningLabels, values: screeningValues });

  const dateCounts = {};
  records.forEach((r) => {
    if (!r.Created_DateTime) return;
    const d = r.Created_DateTime.split(",")[0].trim();
    dateCounts[d] = (dateCounts[d] || 0) + 1;
  });
  const dateLabels = Object.keys(dateCounts).sort();
  renderChart("chartDate", "card-date", "line", { labels: dateLabels, values: dateLabels.map((d) => dateCounts[d]) }, {
    elements: { line: { tension: 0.35, borderColor: "#1F6F6B", borderWidth: 2 }, point: { radius: 3, backgroundColor: "#1F6F6B" } },
  });
}

function render(records) {
  renderKpis(records);
  renderCharts(records);
}
